# Generated by Django 4.1.1 on 2022-11-07 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0002_hashtags_remove_clips_clips_hashtag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clips',
            name='users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='videoapp.users'),
            preserve_default=False,
        ),
    ]
